on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3

      - name: Build reth image
        id: build_image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          build-args: VERSION=1.0.5
          builder: ${{ steps.setup_buildx.outputs.name }}
          cache-from: type=gha,scope=ubuntu
          cache-to: type=gha,mode=max,scope=ubuntu

      - name: Extract reth from image
        uses: shrink/actions-docker-extract@v3
        with:
          image: ${{ steps.build_image.outputs.imageid }}
          path: /root/reth
          destination: out

      - name: Upload reth as release artifact
        uses: softprops/action-gh-release@v2
        with:
          files: out/*
