on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        id: build_image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          builder: ${{ steps.setup_buildx.outputs.name }}
          cache-from: type=gha,scope=ubuntu
          cache-to: type=gha,mode=max,scope=ubuntu

      - name: Extract file from image
        if: startsWith(github.ref, 'refs/tags/v')
        uses: shrink/actions-docker-extract@v3
        with:
          image: ${{ steps.build_image.outputs.imageid }}
          path: /opt/bundle/builtins.tar.gz
          destination: out

      - name: Add version to file name
        if: startsWith(github.ref, 'refs/tags/v')
        working-directory: out
        run: mv builtins.tar.gz builtins-${{ github.ref_name }}.tar.gz

      - name: Upload file as release artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: out/*
